### ISSUE TITLE
reputation_handler_class and support for more content types

### ISSUE THREAD

**Issue by Ralle** [xfrocks/bdReputation#2]
I want to make reputation as widely supported as the like system. Therefore, I would like to expand the post_id to a content_type and content_id and make an abstract class to inherit from when expanding what can be repped. I will do it myself unless you do it first.

**Comment by daohoangson** [comment]
That's an awesome idea. Please go ahead, I'm currently busy with other
projects. Let me know if I can be of any help though. Good luck.

**Comment by Ralle** [comment]
You said you were refactoring for XF 1.2. What can I expect to be changed? Are you "fixing" all the curly brackets so they are on new lines? :smile:

**Comment by ghost** [comment]
The refactor has already been done. That includes dropping support for
XenForo 1.1 which basically means moving on to use template modification
instead of hooks. And yes, I did update the code to follow PSR-2 hah!
